language: node_js
node_js:
- '4.0'
script: npm run-script test-codecov
deploy:
  provider: npm
  email: tech@cargomedia.ch
  api_key:
    secure: G9DoR/WeA4T465/50ueCb7AjIKWF+tYYMqVlaWhhhauFIG0v9SnaiXallaSIk1ORW4l0PAaANZtvxiEPjU6KrbfOyi5mFdhzlRnFWAJkV7pQSroARnRgx31zjN231VB72QgbKI2JV3aJd1ZAlxrew1cgOGGNd0qITSd8vUKzqdBwgtRaLdHmXRcxUdXypsOiI3IfZdK4R4J1WOLoNoJxWaADubAJLJDEn4XIMMJxcdivDdiqkwLPWJvSV+6H6XC+i391wHKnrO9Q15pQlNKhOgwLG2IHYwxEX0+16wDW93izBDcgWOsMm8gQgIl/tVR2UuoHr6WhjlZzLuQIAyRuzxFH+CT54vjxqOwfMLxF4G2G0pGRW3H+W6872Caz+QLznhnkWbivoMUY3BDZ0D4ewXCeiXTPKmpsNcfxxfHoIxRCmKLQ2Ds2xZ+FZXRt6pKTlkTsEx1zGtDnA1N1ha9z3UHchTbvtRlAHxmVC1GBqn4PPeYgIWyI0/pJ5hsSB2/pMxdrurIDDg2rIpv0BXGBgpdYI9/RzkGvmrNCsSZkCIiLivwZEkgJhe0hPXMir/jknWZd7cXS1eCDqk3hrEBOIGwaz+Vl1R+Q6JbEsXVixM03hERzaprBfeg1orX38eeGVnXIMqES1A/Jg0H0xPR69nIllI9tKYJ6GoH5it7oRk4=
  on:
    tags: true
    repo: cargomedia/janus-cluster-manager
