language: node_js
node_js:
- '4.0'
script: npm run-script test-codecov
deploy:
  provider: npm
  email: tech@cargomedia.ch
  api_key:
    secure: jWVD7lVwAs1EpOMBsh18ljmWuzjQHL6KQ0cuBBSDT5kvHQevSNn/Z6Xz7y7Uc/h5jJKcecbx5La0GkHQOAZnc5Wh+KkWhtw3Rurr9RAqcVj+T+EYe7kZ6jCYciYH/Nikv1PovcXb/Hf+ezGdj34SGwLJvHVB6IHCXr/oF697FK4shW0Ja9qFVwD/3+zRAnKRgiu0RI3YzbN/t6al+iOIadXt2GrYBcCggTCVtf2lf1BPbEc/YhbezW/LAjXji7c5ruHVaAmP5ZGtWNzvTxWdn2/mfh+y1rQJq1nCgYD/3L1u+FYHjMbUtv1LMqwl5wqUNReCMConm0bPiUYpLOIfqTO1irQHdgR1Lr36GzHp+atzbDfyLv1DKrTrcXs6Bdn34PbE6nKxFELxwKZ3zbCRaA61/3tso3gPCiFsnEZmxKbesXSEZVDhVI+priW5tG/516qEMtPMsjsHTEOanB0R9fJYN6q487RAyUEvbrql+CP6r9+V5avhqNZpyBq6HELap/ajBk/KkE+5cmq2k85paw8I/84BEi8IbrAKJAXh+2RsW79DR/24+LBywmrtwfxXGyF2o9fQFoP+oV1NJDQhHXZpiADvcxsdN3nicGSR/GtQpqvhuPqIIx5u9/H5aFko3v2llE3aPAHutteJpIPtru3dRePWTlWPq9wfHxFyMmw=
  on:
    tags: true
    repo: cargomedia/janus-cluster
